name: CI

on: pull_request

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: straw-hat-team/github-actions-workflows/asdf/get-version@538da76f97fc4b8e7f9d753eaf70d971cbc5dfd1 # v1.7.8
        id: opentofu-version
        with:
          plugin-name: opentofu
      - uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: ${{ steps.opentofu-version.outputs.plugin-version }}
          tofu_wrapper: true
      - name: tofu fmt
        run: tofu fmt -check -recursive -diff
