name: CI

on: pull_request

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.7.0
        id: opentofu-version
        with:
          plugin-name: opentofu
      - uses: opentofu/setup-opentofu@v1.0.5
        with:
          tofu_version: ${{ steps.opentofu-version.outputs.plugin-version }}
          tofu_wrapper: true
      - name: tofu fmt
        run: tofu fmt -check -recursive -diff
