name: CI

on: pull_request

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: straw-hat-team/github-actions-workflows/asdf/get-version@538da76f97fc4b8e7f9d753eaf70d971cbc5dfd1 # v1.7.8
        id: opentofu-version
        with:
          plugin-name: opentofu
      - uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6
        with:
          tofu_version: ${{ steps.opentofu-version.outputs.plugin-version }}
          tofu_wrapper: true
      - name: tofu fmt
        run: tofu fmt -check -recursive -diff
