name: CI

on: pull_request

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Terraform Version from .tool-versions
        uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.5.0
        id: terraform-version
        with:
          plugin-name: terraform

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: ${{ steps.terraform-version.outputs.plugin-version }}

      - name: Terraform format
        run: terraform fmt -check -recursive .
